In [1]:
import pandas as pd
import os

In [2]:
data_path = 'D:/Orange/Episafe/final-data'

In [3]:
dataframes=[]
for i in  os.listdir(data_path):
    path = os.path.join(data_path,i).replace(os.path.sep,'/')
    dataframe = pd.read_csv(path)
    dataframes.append(dataframe)

final_data = pd.concat(dataframes,ignore_index=True)

In [4]:
final_data

,Unnamed: 0.1,Unnamed: 0,utc_timestamp,acc_x,acc_y,acc_z,acc_mag,bvp,eda,hr,temp,folder,client_id,date,time_slot,label
0,0,0,1.573699e+09,19.003155,-1.996539,58.996271,61.013131,-21.489194,0.170908,83.851998,35.389885,1,1869,2019_11_14,02_40_00,0
1,1,1,1.573699e+09,19.003155,-1.996539,58.996271,61.013131,-21.247182,0.170908,83.851998,35.389885,1,1869,2019_11_14,02_40_00,0
2,2,2,1.573699e+09,19.003155,-1.996539,58.996271,61.013131,-20.924499,0.170908,83.851998,35.389885,1,1869,2019_11_14,02_40_00,0
3,3,3,1.573699e+09,19.003155,-1.996539,58.996271,61.013131,-20.521146,0.170489,83.851998,35.389885,1,1869,2019_11_14,02_40_00,0
4,4,4,1.573699e+09,19.003155,-1.996539,58.996271,61.013131,-19.956451,0.170489,83.851998,35.389885,1,1869,2019_11_14,02_40_00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8447995,76795,76795,1.585787e+09,58.063422,-10.999762,18.938058,61.054594,-19.843519,0.374406,89.676383,33.210034,125,1869,2020_04_02,00_10_00,0
8447996,76796,76796,1.585787e+09,58.183486,-10.999762,19.000700,61.185098,-20.485836,0.374406,89.677595,33.210034,125,1869,2020_04_02,00_10_00,0
8447997,76797,76797,1.585787e+09,58.434055,-10.999762,19.000700,61.420007,-21.385079,0.374406,89.678806,33.210034,125,1869,2020_04_02,00_10_00,0
8447998,76798,76798,1.585787e+09,58.679405,-10.999762,19.000700,61.654916,-22.369964,0.374406,89.681229,33.210034,125,1869,2020_04_02,00_10_00,0
8447999,76799,76799,1.585787e+09,58.929974,-10.999762,19.000700,61.889825,-23.568954,0.374406,89.682441,33.210034,125,1869,2020_04_02,00_10_00,0

In [6]:
final_data['label'].value_counts()

label
0    8448000
Name: count, dtype: int64

In [11]:
path1 = 'D:/Orange/Episafe_local/data/parquet/train/1869/000/UTC-2019_11_11-19_40_00.parquet'
path2 = 'D:/Orange/Episafe/generated-data/1869_001.csv'

In [12]:
data_p = pd.read_parquet(path1)
data_c = pd.read_csv(path2)

In [9]:
data_p

,utc_timestamp,acc_x,acc_y,acc_z,acc_mag,bvp,eda,hr,temp
0,1.573501e+09,49.998417,-33.996502,-16.996712,61.808964,-21.381938,0.123117,80.027020,33.269879
1,1.573501e+09,49.866308,-33.996502,-16.996712,61.703277,-21.829410,0.123117,80.027020,33.269879
2,1.573501e+09,49.617943,-33.996502,-16.996712,61.502471,-22.276882,0.123117,80.027020,33.269879
3,1.573501e+09,49.364294,-33.996502,-16.996712,61.306949,-22.724354,0.123117,80.025800,33.269879
4,1.573501e+09,49.115929,-33.996502,-16.996712,61.106144,-23.107901,0.123117,80.025800,33.269879
...,...,...,...,...,...,...,...,...,...
76795,1.573502e+09,30.002395,-33.996502,44.000667,62.178869,-5.848274,0.120803,79.641369,33.309852
76796,1.573502e+09,30.002395,-33.996502,44.000667,62.178869,-5.976123,0.120803,79.640149,33.309852
76797,1.573502e+09,30.002395,-33.996502,44.000667,62.178869,-6.040048,0.120803,79.640149,33.309852
76798,1.573502e+09,30.002395,-33.996502,44.000667,62.178869,-6.167897,0.120803,79.638929,33.309852
76799,1.573502e+09,30.002395,-33.996502,44.000667,62.178869,-6.359670,0.120803,79.637708,33.309852

In [13]:
data_c

,Unnamed: 0,utc_timestamp,acc_x,acc_y,acc_z,acc_mag,bvp,eda,hr,temp,path
0,0,1.573699e+09,19.003155,-1.996539,58.996271,61.013131,-21.489194,0.170908,83.851998,35.389885,D:/Orange/Episafe_local/data/parquet/train/186...
1,1,1.573699e+09,19.003155,-1.996539,58.996271,61.013131,-21.247182,0.170908,83.851998,35.389885,D:/Orange/Episafe_local/data/parquet/train/186...
2,2,1.573699e+09,19.003155,-1.996539,58.996271,61.013131,-20.924499,0.170908,83.851998,35.389885,D:/Orange/Episafe_local/data/parquet/train/186...
3,3,1.573699e+09,19.003155,-1.996539,58.996271,61.013131,-20.521146,0.170489,83.851998,35.389885,D:/Orange/Episafe_local/data/parquet/train/186...
4,4,1.573699e+09,19.003155,-1.996539,58.996271,61.013131,-19.956451,0.170489,83.851998,35.389885,D:/Orange/Episafe_local/data/parquet/train/186...
...,...,...,...,...,...,...,...,...,...,...,...
76795,76795,1.573700e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D:/Orange/Episafe_local/data/parquet/train/186...
76796,76796,1.573700e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D:/Orange/Episafe_local/data/parquet/train/186...
76797,76797,1.573700e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D:/Orange/Episafe_local/data/parquet/train/186...
76798,76798,1.573700e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D:/Orange/Episafe_local/data/parquet/train/186...
76799,76799,1.573700e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,D:/Orange/Episafe_local/data/parquet/train/186...

In [ ]:
path1 = 'D:/Orange/Episafe_local/data/parquet/train/1869/000/UTC-2019_11_11-19_40_00.parquet'